Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 110
AllCops:
  TargetRubyVersion: 2.6.3
Style/StringLiterals:
  EnforcedStyle: double_quotes
Metrics/BlockLength:
  CountComments: false
  Max: 25
  ExcludedMethods: ["describe", "context"]
